name: calendar_time
description: Implementation of MomentJS's calendar time, plus a bunch of other helper methods.
version: 1.0.0
author: Ryan Knell <rknell@snappyapps.com.au>
homepage: https://github.com/rknell/calendar_time

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  intl: ^0.16.1

dev_dependencies:
  test:
  pedantic: ^1.9.2